# Generated by Django 4.0.3 on 2022-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Sr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
