# Generated by Django 4.0.3 on 2022-05-31 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_book_list_syllabus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
